import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/ui/nav";
import Footer from "@/ui/footer";
import SessionProvider from "../lib/sessionProvider";
import { getServerSession } from "next-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()

  return (
    <html lang="en">
    <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
    </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <SessionProvider session={session}>
          <Nav/>
          <main>{children}</main>
          <Footer/>
        </SessionProvider>
      </body>

    </html>
  );
}
